modLoader = "javafml"
loaderVersion = "[33,)"
issueTrackerURL = "${mod_issue_tracker_url}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_display_name}"
authors = "${mod_authors}"
credits = "${mod_credits}"
description = '''
${mod_description}
'''
logoFile = "icon.png"

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[36.1.65,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "architectury"
mandatory = true
versionRange = "[1.15.13,)"
ordering = "AFTER"
side = "BOTH"
